#Build stage

FROM node:14-alpine as build-stage 

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

#Run stage

FROM nginx:stable-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

ENV REACT_APP_BACKEND_URL=http://localhost

CMD ["nginx", "-g", "daemon off;"]

