apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: sachinjai02/kub-learnings:user-app-v1    
          imagePullPolicy: Always
        - name: auth
          image: sachinjai02/kub-learnings:auth-app-v1    
          imagePullPolicy: Always
