apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-057649e9b5818b319

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: users-pv
      