#version: "3.8" 
## optional in latest docker-compose
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=sachin
    #  - MONGO_INITDB_ROOT_PASSWORD=secret
    # MONGO_INITDB_ROOT_USERNAME: sachin
    env_file:
      - ./env/mongo.env
  
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     - NODE_ENV=development
    ports:
      - '80:80'    
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ./env/backend.env   
    depends_on:
      - mongodb  
volumes:
  data:
  logs:

   
  