services:
  webserver:
    build: 
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    depends_on: 
      - phpapp
      
  phpapp:
    build: 
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    # volumes:
      # - ./src:/var/www/html:delegated
    depends_on: 
      - mysqldb

  mysqldb:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
      
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:    
      - ./src:/var/www/html:delegated
      
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:    
      - ./src:/var/www/html:delegated
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
    - mysqldb
  
  npm:
    image: node
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:    
      - ./src:/var/www/html:delegated